<?php

declare(strict_types=1);

namespace LaravelAnalyzer\Refactoring;

/**
 * Generates a phased refactoring plan from analyzer results.
 *
 * Each phase corresponds to one issue mapped to a refactoring.guru technique.
 * Phases are ordered: CRITICAL → HIGH → MEDIUM → LOW.
 * Issues without a mapped technique are collected in an appendix.
 *
 * Output: Markdown string ready to save as REFACTORING_PLAN.md.
 */
class RefactoringPlanGenerator
{
    private TechniqueMapper $mapper;

    public function __construct(?TechniqueMapper $mapper = null)
    {
        $this->mapper = $mapper ?? new TechniqueMapper();
    }

    /**
     * @param  array  $results   Analyzer results array (from Application::$results)
     * @param  string $project   Project name (basename of path)
     * @return string            Markdown content
     */
    public function generate(array $results, string $project): string
    {
        $allIssues   = $this->collectAndPrioritize($results);
        $pairs       = $this->mapper->mapAll($allIssues);
        $unmapped    = $this->collectUnmapped($allIssues, $pairs);

        $date  = date('Y-m-d');
        $total = count($pairs);

        $md  = "# 🔧 Refactoring Plan — {$project}\n\n";
        $md .= "> Generated: {$date} | Phases: {$total} | Based on: [refactoring.guru](https://refactoring.guru/refactoring/techniques)\n\n";
        $md .= "---\n\n";
        $md .= "## How to use this plan\n\n";
        $md .= "1. Work through phases **in order** — higher severity first.\n";
        $md .= "2. Before each phase: write the unit test described in **Test Requirement**.\n";
        $md .= "3. Apply the refactoring technique.\n";
        $md .= "4. Run the **Regression Check** command — all existing tests must remain green.\n";
        $md .= "5. Commit and open a PR for that phase using the suggested branch name.\n\n";
        $md .= "---\n\n";

        if (empty($pairs)) {
            $md .= "_No refactoring phases generated — no issues matched known techniques._\n";
            return $md;
        }

        foreach ($pairs as $index => $pair) {
            $md .= $this->renderPhase($index + 1, $pair['issue'], $pair['technique']);
        }

        if (!empty($unmapped)) {
            $md .= $this->renderAppendix($unmapped);
        }

        $md .= "---\n\n";
        $md .= "_Generated by [Laravel Best Practices Analyzer](https://github.com/lucasgio/laravel-analyzer)_\n";

        return $md;
    }

    /**
     * Returns a suggested git branch name for a single phase.
     */
    public function suggestBranch(array $issue, array $technique): string
    {
        $slug     = $technique['branch_slug'];
        $file     = basename($issue['file'], '.php');
        $file     = strtolower(preg_replace('/([A-Z])/', '-$1', lcfirst($file)));
        $file     = preg_replace('/[^a-z0-9\-]/', '-', $file);
        $file     = trim(preg_replace('/-+/', '-', $file), '-');

        return "refactor/{$slug}-{$file}";
    }

    // ------------------------------------------------------------------

    private function renderPhase(int $number, array $issue, array $technique): string
    {
        $severity  = $issue['severity'];
        $file      = $issue['file'];
        $line      = $issue['line'] > 0 ? ":{$issue['line']}" : '';
        $message   = $issue['message'];
        $branch    = $this->suggestBranch($issue, $technique);
        $severityIcon = match ($severity) {
            'CRITICAL' => '🔴',
            'HIGH'     => '🟠',
            'MEDIUM'   => '🟡',
            default    => '⚪',
        };

        $md  = "## Phase {$number}: {$technique['name']}\n\n";
        $md .= "**Severity:** {$severityIcon} {$severity} &nbsp;|&nbsp; ";
        $md .= "**Risk:** {$technique['risk']} &nbsp;|&nbsp; ";
        $md .= "**Technique:** [{$technique['name']}]({$technique['url']})\n\n";

        $md .= "### Issue\n\n";
        $md .= "- **File:** `{$file}{$line}`\n";
        $md .= "- **Detail:** {$message}\n\n";

        $md .= "### What & Why\n\n";
        $md .= "{$technique['description']}\n\n";

        $md .= "### Steps\n\n";
        foreach ($technique['steps'] as $i => $step) {
            $md .= ($i + 1) . ". {$step}\n";
        }
        $md .= "\n";

        $md .= "### Test Requirement\n\n";
        $md .= "> **Write this test BEFORE refactoring.** It becomes your regression guard.\n\n";
        $md .= "{$technique['test_hint']}\n\n";
        $md .= "```bash\n# Run your test to confirm it passes before you start:\n./vendor/bin/phpunit --filter " . basename($file, '.php') . "Test\n```\n\n";

        $md .= "### Regression Verification\n\n";
        $md .= "After applying the refactoring, run the **full test suite**:\n\n";
        $md .= "```bash\n./vendor/bin/phpunit --no-coverage\n```\n\n";
        $md .= "All tests must be **green**. If any test fails, revert and re-examine the refactoring.\n\n";

        $md .= "### Git Branch\n\n";
        $md .= "```bash\ngit checkout -b {$branch}\n```\n\n";

        $md .= "---\n\n";

        return $md;
    }

    private function renderAppendix(array $unmapped): string
    {
        $md  = "## Appendix — Issues Without a Mapped Technique\n\n";
        $md .= "These issues were found but could not be automatically matched to a refactoring.guru technique. ";
        $md .= "Address them manually after completing the phases above.\n\n";

        foreach ($unmapped as $issue) {
            $icon = match ($issue['severity']) {
                'CRITICAL' => '🔴',
                'HIGH'     => '🟠',
                'MEDIUM'   => '🟡',
                default    => '⚪',
            };
            $line = $issue['line'] > 0 ? ":{$issue['line']}" : '';
            $md  .= "- {$icon} **[{$issue['file']}{$line}]** {$issue['message']}\n";
        }

        $md .= "\n";

        return $md;
    }

    /**
     * Collects all issues from all modules and sorts by severity: CRITICAL → HIGH → MEDIUM → LOW.
     */
    private function collectAndPrioritize(array $results): array
    {
        $order  = ['CRITICAL' => 0, 'HIGH' => 1, 'MEDIUM' => 2, 'LOW' => 3];
        $issues = [];

        foreach ($results as $result) {
            if (isset($result['error'])) continue;
            foreach ($result['issues'] ?? [] as $issue) {
                $issues[] = $issue;
            }
        }

        usort($issues, fn($a, $b) =>
            ($order[$a['severity']] ?? 4) <=> ($order[$b['severity']] ?? 4)
        );

        return $issues;
    }

    /**
     * Returns issues that did not match any technique.
     */
    private function collectUnmapped(array $allIssues, array $pairs): array
    {
        $mappedMessages = array_column(array_column($pairs, 'issue'), 'message');

        return array_values(array_filter($allIssues, fn($i) =>
            !in_array($i['message'], $mappedMessages, true)
        ));
    }
}
