<?php

declare(strict_types=1);

namespace LaravelAnalyzer\Config;

/**
 * Distinguishes developer-written code from Laravel framework scaffolding.
 *
 * Analyzers should call isDevFile() before processing a PHP file to avoid
 * generating false positives on boilerplate that developers never touch.
 *
 * Custom exclusions can be added via .laravel-analyzer.json in the project root:
 *
 *   {
 *     "exclude": ["app/Legacy/OldKernel.php", "app/Http/Middleware/Custom*"]
 *   }
 */
class LaravelFileFilter
{
    /**
     * Relative paths (from project root) that are pure Laravel scaffold.
     * Glob patterns are supported (fnmatch).
     */
    private const FRAMEWORK_PATHS = [
        // HTTP / Console kernels (Laravel ≤10)
        'app/Http/Kernel.php',
        'app/Console/Kernel.php',

        // Exception handler
        'app/Exceptions/Handler.php',

        // Framework middleware — generated by artisan, almost never modified
        'app/Http/Middleware/Authenticate.php',
        'app/Http/Middleware/RedirectIfAuthenticated.php',
        'app/Http/Middleware/TrustHosts.php',
        'app/Http/Middleware/TrustProxies.php',
        'app/Http/Middleware/VerifyCsrfToken.php',
        'app/Http/Middleware/EncryptCookies.php',
        'app/Http/Middleware/PreventRequestsDuringMaintenance.php',

        // Default providers — usually empty stubs
        'app/Providers/BroadcastServiceProvider.php',

        // Laravel 11 bootstrap
        'bootstrap/app.php',
        'bootstrap/providers.php',

        // IDE helpers
        '_ide_helper.php',
        '_ide_helper_models.php',
        '.phpstorm.meta.php',

        // Glob patterns
        '_ide_helper*.php',
        '*.stub.php',
    ];

    /** Directories to always exclude regardless of project config */
    private const EXCLUDE_DIRS = [
        'vendor',
        'node_modules',
        '.git',
        'storage',
        'bootstrap/cache',
        'public',
    ];

    private string $projectPath;

    /** @var string[] Extra patterns loaded from .laravel-analyzer.json */
    private array $customExclusions = [];

    public function __construct(string $projectPath)
    {
        $this->projectPath = rtrim($projectPath, '/');
        $this->loadCustomConfig();
    }

    /**
     * Returns true when the file is developer-written code that should be analyzed.
     */
    public function isDevFile(string $absolutePath): bool
    {
        $relative = $this->toRelative($absolutePath);

        foreach (self::FRAMEWORK_PATHS as $pattern) {
            if ($this->matches($relative, $pattern)) {
                return false;
            }
        }

        foreach ($this->customExclusions as $pattern) {
            if ($this->matches($relative, $pattern)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Filters a list of absolute file paths, keeping only developer files.
     *
     * @param  string[] $files
     * @return string[]
     */
    public function filterDevFiles(array $files): array
    {
        return array_values(array_filter($files, fn(string $f) => $this->isDevFile($f)));
    }

    /**
     * Returns the directories that should be excluded from any recursive scan.
     *
     * @return string[]
     */
    public static function excludedDirs(): array
    {
        return self::EXCLUDE_DIRS;
    }

    // ------------------------------------------------------------------

    private function toRelative(string $absolutePath): string
    {
        $base = $this->projectPath . '/';
        if (str_starts_with($absolutePath, $base)) {
            return substr($absolutePath, strlen($base));
        }
        return $absolutePath;
    }

    private function matches(string $relative, string $pattern): bool
    {
        // Exact match
        if ($relative === $pattern) {
            return true;
        }

        // fnmatch glob (e.g. "_ide_helper*.php")
        if (fnmatch($pattern, $relative)) {
            return true;
        }

        // Match basename only for simple glob patterns (no directory separator)
        if (!str_contains($pattern, '/') && fnmatch($pattern, basename($relative))) {
            return true;
        }

        return false;
    }

    private function loadCustomConfig(): void
    {
        $configPath = $this->projectPath . '/.laravel-analyzer.json';
        if (!file_exists($configPath)) {
            return;
        }

        $raw = file_get_contents($configPath);
        if ($raw === false) {
            return;
        }

        $config = json_decode($raw, true);
        if (!is_array($config) || empty($config['exclude'])) {
            return;
        }

        $this->customExclusions = array_map('strval', (array) $config['exclude']);
    }
}
